Improvements to scripts, add PBE strings

diff --git a/2019/validation-scripts/process_track_results b/2019/validation-scripts/process_track_results
--- a/2019/validation-scripts/process_track_results
+++ b/2019/validation-scripts/process_track_results
@@ -7,6 +7,12 @@
 
 BENCHDIR=$1
 
+if [ ! -d "$BENCHDIR" ];
+then
+  echo "Error: Bad root benchmark directory specified $BENCHDIR"
+  exit 1
+fi
+
 # $BENCHDIR is path to sygus benchmarks, which is has a parallel hierarchy to the job output space. This should be the benchmarks that the track was run on.
 
 echo "Solver,Benchmark,Result,Time,Exprs"
diff --git a/2019/validation-scripts/process_tracks b/2019/validation-scripts/process_tracks
--- a/2019/validation-scripts/process_tracks
+++ b/2019/validation-scripts/process_tracks
@@ -10,6 +10,12 @@ ROOTBENCHDIR=$1
 
 echo "Root benchmark directory set to $ROOTBENCHDIR"
 
+if [ ! -d "$ROOTBENCHDIR" ];
+then
+  echo "Error: Bad root benchmark directory specified $ROOTBENCHDIR"
+  exit 1
+fi
+
 # $ROOTBENCHDIR is path to sygus benchmarks over all tracks.
 # For 2019, this should be the directory https://github.com/SyGuS-Org/benchmarks/tree/master/comp/2019.
 
