Improve, fix

diff --git a/2019/validation-scripts/process_result b/2019/validation-scripts/process_result
--- a/2019/validation-scripts/process_result
+++ b/2019/validation-scripts/process_result
@@ -8,11 +8,23 @@ SEMANTIC_SOLVER=cvc4
 SOLVEROUT=$1
 SYGUSBENCHNAME=$2
 
+# Ensure that files exist
+if [ ! -e "$SOLVEROUT" ];
+then
+  echo "error (could not find solver output file)"
+  exit 1
+fi
+if [ ! -e "$SYGUSBENCHNAME" ];
+then
+  echo "error (could not find reference sygus file)"
+  exit 1
+fi
+
 # Run the SynthLib2Tester tool to check grammar
 #echo "[debug] Run SynthLib2Tester to check grammar..."
 SynthLib2Tester $SOLVEROUT $SYGUSBENCHNAME > temp-check-syntax.txt
 
-cat temp-check-syntax.txt | grep result
+#cat temp-check-syntax.txt | grep result
 
 # If it adheres to grammar (is this right?)
 if grep -q adheres=true temp-check-syntax.txt;
