More fixes

diff --git a/2019/validation-scripts/process_result b/2019/validation-scripts/process_result
--- a/2019/validation-scripts/process_result
+++ b/2019/validation-scripts/process_result
@@ -23,36 +23,47 @@ then
   exit 1
 fi
 
-
 # for simple debugging
 #echo "FILE-OK"
 #exit 1;
 
 
-# Run the SynthLib2Tester tool to check grammar
-#echo "[debug] Run SynthLib2Tester to check grammar..."
-SynthLib2Tester $SOLVEROUT $SYGUSBENCHNAME > temp-check-syntax.txt
-
-#cat temp-check-syntax.txt | grep result
-
-# If it adheres to grammar (is this right?)
-if grep -q adheres=true temp-check-syntax.txt;
+# did the solver produce a solution?
+if grep -q define-fun $SOLVEROUT;
 then
-  #echo "[debug] Run SMT solver to check semantic correctness..."
-  ulimit -t $SEMANTIC_CHECK_TIMEOUT;$SEMANTIC_SOLVER --lang=smt2 __sygus_grmrchecker_output.smt >& temp-check-semantic.txt
-  # grep for unsat/sat here
-  if grep -q unsat temp-check-semantic.txt;
-  then
-    echo "FAIL-SEMANTIC-UNSAT"
-  elif grep -q sat temp-check-semantic.txt;
-  then
-    echo "SUCCESS"
-  else
-    echo "FAIL-SEMANTIC"
-  fi
-else
-  echo "FAIL-SYNTAX"
+  # for simple debugging
+  echo "SOLVED"
+  exit 1;
 
+  # Run the SynthLib2Tester tool to check grammar
+  #echo "[debug] Run SynthLib2Tester to check grammar..."
+  SynthLib2Tester $SOLVEROUT $SYGUSBENCHNAME > temp-check-syntax.tmp
+
+  #cat temp-check-syntax.txt | grep result
+
+  # If it adheres to grammar (is this right?)
+  if grep -q adheres=true temp-check-syntax.tmp;
+  then
+    #echo "[debug] Run SMT solver to check semantic correctness..."
+    ulimit -t $SEMANTIC_CHECK_TIMEOUT;$SEMANTIC_SOLVER --lang=smt2 __sygus_grmrchecker_output.smt >& temp-check-semantic.txt
+    # grep for unsat/sat here
+    if grep -q unsat temp-check-semantic.txt;
+    then
+      echo "FAIL-SEMANTIC-UNSAT"
+    elif grep -q sat temp-check-semantic.txt;
+    then
+      echo "SUCCESS"
+    else
+      echo "FAIL-SEMANTIC"
+    fi
+  else
+    echo "FAIL-SYNTAX"
+    #echo "FAIL SYNTAX:"
+    #cat temp-check-syntax.tmp
+  fi
+  rm temp-check-syntax.tmp
+else
+    echo "UNSOLVED"
 fi
 
 #echo "[debug] Finished"
